version: "3"
services:
  rabbitmq:
    image: "rabbitmq:3.12-alpine"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  frontend:
    build:
      context: "./frontend/"
      dockerfile: "./Dockerfile"
    ports:
      - "3000:3000"
    environment:
      - MANAGEMENT_HOST=http://management:8080

  management:
    build:
      context: "./management/"
      dockerfile: "./Dockerfile"
    ports:
      - "8080:8080"
    environment:
      - RMQ_HOST=rabbitmq
      - RMQ_PORT=5672
      - RMQ_USER=guest
      - RMQ_PASSWORD=guest

  gameserver:
    build:
      context: "./gameserver/"
      dockerfile: "./Dockerfile"
    ports:
      - "8081:8080"
    environment:
      - RMQ_HOST=rabbitmq
