apiVersion: v1
kind: Service
metadata:
  name: gameserver-service
spec:
  selector:
    app: gameserver
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gameserver-deployment
spec:
  selector:
    matchLabels:
      app: gameserver
  replicas: 1
  template:
    metadata:
      labels:
        app: gameserver
    spec:
      containers:
        - name: gameserver
          image: registry.reset.inso-w.at/2023ws-ase-pr-group/23ws-ase-pr-inso-04/gameserver:latest
          ports:
            - containerPort: 8080
          env:
            - name: RMQ_HOST
              value: "http://23ws-ase-pr-inso-04.apps.student.inso-w.at:5672"
      imagePullSecrets:
        - name: secret-dockercfg
