apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "23ws-ase-pr-inso-04-ingress"
  namespace: 23ws-ase-pr-inso-04
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: "23ws-ase-pr-inso-04.apps.student.inso-w.at"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: management-service
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gameserver-service
                port:
                  number: 8081
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 3000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rabbitmq-service
                port:
                  number: 5672
