apiVersion: v1
kind: Service
metadata:
  name: management-service
spec:
  selector:
    app: management
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: management-deployment
spec:
  selector:
    matchLabels:
      app: management
  replicas: 1
  template:
    metadata:
      labels:
        app: management
    spec:
      containers:
        - name: management
          image: registry.reset.inso-w.at/2023ws-ase-pr-group/23ws-ase-pr-inso-04/management:latest
          resources:
            requests:
              memory: "150Mi"
              cpu: "200m"
              ephemeral-storage: "500Mi"
            limits:
              memory: "300Mi"
              cpu: "400m"
              ephemeral-storage: "1000Mi"

          ports:
            - containerPort: 8080
          env:
            - name: RMQ_HOST
              value: "http://23ws-ase-pr-inso-04.apps.student.inso-w.at/rabbitmq"
      imagePullSecrets:
        - name: secret-dockercfg
